services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    
    # WE INJECT THE UUID HERE
    command: tunnel run ${TUNNEL_UUID}
    
    volumes:
      # Use the ENV variable to find the correct secret file
      - /media/storage/secrets/${TUNNEL_UUID}.json:/etc/cloudflared/credentials.json:ro
      
      # Mount the generic config
      - ../configs/cloudflared-tunnel.yaml:/etc/cloudflared/config.yml:ro
    networks:
      - default