services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    network_mode: "host" # Critical for DHCP and proper Client ID visibility
    environment:
      - TZ=Asia/Kolkata
      - WEBPASSWORD=${PIHOLE_PASSWORD} # Change this initial password!
    volumes:
      -  /media/storage/data/pihole/etc-pihole:/etc/pihole
      -  /media/storage/data/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN # Required for DHCP
    restart: unless-stopped