services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /media/storage/data/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    environment:
      - TZ=Asia/Kolkata
      - POSTGRES_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:5432/homeassistant
      - TUYA_ACCESS_ID=${TUYA_ACCESS_ID}
      - TUYA_ACCESS_SECRET=${TUYA_ACCESS_SECRET}
      - TUYA_COUNTRY_CODE=${TUYA_COUNTRY_CODE}
    restart: unless-stopped
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    network_mode: host
    depends_on:
      - mosquitto


  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2
    volumes:
      - /media/storage/data/homeassistant/mosquitto:/mosquitto/config
      - /media/storage/data/homeassistant/mosquitto/data:/mosquitto/data
      - /media/storage/data/homeassistant/mosquitto/log:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"
    restart: unless-stopped