services:
  postgres:
    container_name: ha-postgres
    image: postgres:15-alpine
    volumes:
      - /media/storage/data/postgres/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=homeassistant
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    ports:
      - "5050:80"  
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    depends_on:
      - postgres
    volumes:
      - /media/storage/data/pgadmin:/var/lib/pgadmin